# seta a rede que os containers irão conversar
networks:
  taiff_network: {}

services: 
  #Container do banco de dados 
  db:
    # Seta o nome do container
    container_name: db
    #imagem de origem
    image: mysql:5.7
    #porta que irá operar
    ports:
      - 3306:3306
    #rede que irá estar conectado
    networks:
      - taiff_network
    #configuraçoes do mySql
    environment:
      - MYSQL_ROOT_PASSWORD=root 
    volumes:
    - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql

  #container do frontend
  frontend:
    build: https://github.com/5ilasEliaquim/front-consumo.git
    #imagem de origem
    image: front-end
    #porta que irá operar
    ports:
      - 3000:3000
    #rede que irá estar conectado
    networks:
      - taiff_network

  #container do backend
  backend-temperatura:
    build: https://github.com/5ilasEliaquim/api-temperatura.git
    #Depende que o banco de dados tenha subido para subir em sequencia
    depends_on: 
      - db
    #imagem de origem
    image: backend-temperatura
    #porta que irá operar
    ports: 
      - 8081:8081
    #rede que irá estar conectado
    networks:
      - taiff_network

  #container do backend
  backend-posicionamento:
    build: https://github.com/5ilasEliaquim/api-posicionamento.git
    #Depende que o banco de dados tenha subido para subir em sequencia
    depends_on: 
      - db
    #imagem de origem
    image: backend-posicionamento
    #porta que irá operar
    ports: 
      - 8080:8080
    #rede que irá estar conectado
    networks:
      - taiff_network